[package]
edition = { workspace = true }
name = "js-sys-macro"
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
js-bindgen-macro-shared = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
js-bindgen-ld-shared = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
rand = { workspace = true }
similar-asserts = { workspace = true }
syn = { workspace = true }
wasmparser = { workspace = true }
