[build]
target = "wasm32-unknown-unknown"
#target = "wasm64-unknown-unknown"

#[unstable]
#build-std = ["panic_abort", "std"]

[target.'cfg(all(target_family = "wasm", any(target_os = "none", target_os = "unknown")))']
linker = "../common/linker.cmd"
runner = "../common/runner.cmd"

[env]
JBG_LOCAL_DEV = "1"
