[build]
target = "wasm32-unknown-unknown"

[target.'cfg(all(target_family = "wasm", any(target_os = "none", target_os = "unknown")))']
linker = "../cargo-shim/linker.cmd"
runner = "../cargo-shim/runner.cmd"
