[package]
edition = { workspace = true }
include = { workspace = true }
license = { workspace = true }
name = "js-bindgen-shared"
rust-version = { workspace = true }

[dependencies]
memmap2 = { workspace = true }

[lints]
workspace = true
