[package]
edition = { workspace = true }
name = "js-bindgen-runner"
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
js-bindgen-ld-shared = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
wasmparser = { workspace = true }

[lints]
workspace = true
