[package]
edition = { workspace = true }
include = { workspace = true }
name = "js-bindgen-test-macro"
rust-version = "1.87"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, features = ["proc-macro"] }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }

[lints]
workspace = true
