[package]
edition = { workspace = true }
name = "js-bindgen-test-macro"
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
js-bindgen-macro-shared = { workspace = true }
proc-macro2 = { workspace = true, features = ["proc-macro"] }

[lints]
workspace = true
