[package]
edition = { workspace = true }
license = { workspace = true }
name = "wasm-ld-opt"
publish = false

[dependencies]
anyhow = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
