[build]
target = "wasm32-unknown-unknown"

[target.'cfg(all(target_family = "wasm", any(target_os = "none", target_os = "unknown")))']
linker = "../linker-shim/linker"

[env]
JS_BINDGEN_CACHE_DISABLE_CHECK = "1"
