[package]
edition = { workspace = true }
license = { workspace = true }
name = "js-bindgen-ld-shared"
rust-version = "1.91"

[dependencies]
js-bindgen-shared = { workspace = true }
object = { workspace = true }
wasmparser = { workspace = true }

[lints]
workspace = true
