[package]
edition.workspace = true
name = "js-bindgen-test-macro"
rust-version.workspace = true
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
js-bindgen-macro-shared = { workspace = true }

[lints]
workspace = true
