[package]
name = "js-bindgen-test-macro"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
js-bindgen-macro-shared = { workspace = true }

[lints]
workspace = true
