[package]
edition.workspace = true
name = "js-bindgen-test"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
js-bindgen-test-macro = { workspace = true }
js-sys = { workspace = true }

[lints]
workspace = true
