[package]
edition = { workspace = true }
license = { workspace = true }
name = "js-sys"
rust-version = { workspace = true }

[dependencies]
js-bindgen = { workspace = true }
js-sys-macro = { workspace = true }
