[package]
edition = "2021"
name = "js-bindgen"
rust-version = "1.59"
version = "0.0.0"

[lib]
proc-macro = true

[features]
bootstrap = ["dep:ar_archive_writer", "dep:proc-macro2", "dep:sanitize-filename", "dep:syn"]

[dependencies]
ar_archive_writer = { version = "0.5", optional = true }
proc-macro2 = { version = "1", optional = true, features = ["span-locations"] }
sanitize-filename = { version = "=0.7.0-beta", optional = true }
syn = { version = "2", optional = true, default-features = false, features = [
	"parsing",
	"proc-macro",
] }
