name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_wasm32:
    name: wasm32
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      # llvm-mc used
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          # rustc 1.93.0
          version: "21.1.8"
      - name: Test js-sys
        working-directory: client
        run: cargo test -p js-sys --target wasm32-unknown-unknown
      - name: Test web-sys
        working-directory: client
        run: cargo test -p web-sys --target wasm32-unknown-unknown

  test_wasm64:
    name: wasm64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      # llvm-mc used
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          # rustc 1.93.0
          version: "21.1.8"
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
      - name: Test js-sys
        working-directory: client
        run: cargo +nightly test -p js-sys --target wasm64-unknown-unknown -Zbuild-std=panic_abort,std
      - name: Test web-sys
        working-directory: client
        run: cargo +nightly test -p web-sys --target wasm64-unknown-unknown -Zbuild-std=panic_abort,std

